# Reference of settings:
# https://github.com/golangci/golangci-lint/blob/master/.golangci.example.yml

# To remedy '<file>: File is not `goimports`-ed (goimports)' do:
# goimports -w -local dev.azure.com/skfdc,skfdc.visualstudio.com,github.com/SKF <file>

run:
  # timeout for analysis, e.g. 30s, 5m, default is 1m
  deadline: 5m

  concurrency: 4

  skip-files:
    - _test.go

  skip-dirs: []

linters-settings:
  errcheck:
    # default is false: such cases aren't reported by default.
    check-blank: true
  govet:
    # report about shadowed variables
    check-shadowing: true
  goimports:
    # put imports beginning with prefix after 3rd-party packages;
    # it's a comma-separated list of prefixes
    local-prefixes: github.com/j-sv
  gocyclo:
    # minimal code complexity to report, 30 by default (but we recommend 10-20)
    min-complexity: 20
  gocognit:
    # minimal code complexity to report, 30 by default (but we recommend 10-20)
    min-complexity: 20
  maligned:
    # print struct with more effective memory layout or not, false by default
    suggest-new: true
  dupl:
    # tokens count to trigger issue, 150 by default
    threshold: 150
  lll:
    max-line-length: 140

issues:
  # List of regexps of issue texts to exclude, empty list by default.
  # To see excluded by default patterns execute `golangci-lint run --help`
  # exclude:
  #   - don't use ALL_CAPS in Go names; use CamelCase
  exclude-rules: []

linters:
  disable-all: true
  enable:
    - asciicheck
    - bodyclose
    - deadcode
    - depguard
    - dogsled
    - dupl
    - errcheck
    - exhaustive
    - exportloopref
    - funlen
    - gochecknoglobals
    - gochecknoinits
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - godox
    - goerr113
    - gofmt
    - gofumpt
    - goimports
    - golint # replaced by stylecheck
    # - gomnd
    - gomodguard
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - interfacer
    - lll
    - maligned
    - misspell
    - nakedret
    - nestif
    - noctx
    - nolintlint
    - prealloc
    - rowserrcheck
    - scopelint
    - staticcheck
    - structcheck
    - stylecheck
    - testpackage
    - typecheck
    - unconvert
    - unparam
    - unused
    - varcheck
    - whitespace
    - wsl
